version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    volumes:
      - ./backend:/app 
    environment:
      - FLASK_APP=app.py  
      - FLASK_ENV=development 
    networks:
      - app-network  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    volumes:
      - ./frontend:/src 
    depends_on:
      - backend 
    networks:
      - app-network 
  
networks:
  app-network:
    driver: bridge 