apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kasifzisandocker/zisan-docker-example:frontend-${GITHUB_SHA}
        ports:
        - containerPort: 80
