name: Build and push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout github code
      uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name : Build and Push Docker Image
      run: |
       docker build -t zisandockerhub/flask-app-docker-compose:frontend-${{ github.sha }} -f frontend/Dockerfile frontend/ 
       docker push zisandockerhub/flask-app-docker-compose:frontend-${{ github.sha }}

       docker build -t zisandockerhub/flask-app-docker-compose:backend-${{ github.sha }} -f backend/Dockerfile backend/
       docker push zisandockerhub/flask-app-docker-compose:backend-${{ github.sha }}